# Generated by Django 4.1.5 on 2023-02-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_emaii',
            new_name='user_email',
        ),
    ]
